### ISSUE TITLE
Exclude /images but not /user/pages/images?

### ISSUE THREAD

**Issue by bobrocke** [JonathanWolfe/file-tree-exclude#18] opened 2015-06-12 15:29 UTC
How would I configure to exclude `/images` but not `/user/pages/images`?

Just using `images` excludes them both. Using `/images` and `/images/` shows them both.

**Comment by JonathanWolfe** [comment] 2015-06-12 20:34
Duplicate of #16

**Closed as completed by JonathanWolfe** 2015-06-12 20:34 UTC
